=== piotrgiedziun/university/java_xml/lab3/task5.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="courses">
  <xs:complexType>
    <xs:sequence>
    	<xs:element name="course" maxOccurs="unbounded">
    		<xs:complexType>
    			<xs:sequence>
      				<xs:element name="name">
					  <xs:simpleType>
					    <xs:restriction base="xs:string">
					      <xs:enumeration value="Information systems modelling"/>
					      <xs:enumeration value="Advanced databases"/>
					      <xs:enumeration value="Information systems analysis"/>
					      <xs:enumeration value="Social Communication"/>
					      <xs:enumeration value="Discrete mathematics"/>
					    </xs:restriction>
					  </xs:simpleType>
					</xs:element>
					<xs:element name="lecturer" type="xs:string" />
      			</xs:sequence>
      			<xs:attribute name="id" type="idType" use="required"/>
      		</xs:complexType>
      	</xs:element>
    </xs:sequence> 
  </xs:complexType> 
</xs:element>

<xs:simpleType name="idType">
<xs:restriction base="xs:nonNegativeInteger">
  <xs:minInclusive value="0"/>
  <xs:maxInclusive value="1200"/>
</xs:restriction>
</xs:simpleType>

</xs:schema>

=== piotrgiedziun/university/lab3/task5.xml
<?xml version="1.0" encoding="UTF-8"?>

<courses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="task5.xsd">
	<course id="0">
		<name>Information systems modelling</name>
		<lecturer>Naruto Uzumaki</lecturer>
	</course>
	<course id="1">
		<name>Advanced databases</name>
		<lecturer>Roronoa Zoro</lecturer>
	</course>
	<course id="2">
		<name>Information systems analysis</name>
		<lecturer>Neji Hyuga</lecturer>
	</course>
	<course id="3">
		<name>Social Communication</name>
		<lecturer>Kakashi Hatake</lecturer>
	</course>
	<course id="4">
		<name>Discrete mathematics</name>
		<lecturer>Rock Lee</lecturer>
	</course>
</courses>
